services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: compassbook
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build: .
    command: bash -c "./wait-for-it.sh db:3306 -- rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
      - ./wait-for-it.sh:/app/wait-for-it.sh
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: compassbook
      RAILS_ENV: development
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:
  bundle_data:

networks:
  app-network:
    name: app-network
    driver: bridge
